'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Scratch.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Imports System, System.IO, Microsoft.VisualBasic, System.Reflection
        '''&lt;Assembly: AssemblyTitle(&quot;ΦA1Φ&quot;)&gt; 
        '''&lt;Assembly: AssemblyDescription(&quot;ΦA2Φ&quot;)&gt; 
        '''&lt;Assembly: AssemblyCompany(&quot;ΦA3Φ&quot;)&gt; 
        '''&lt;Assembly: AssemblyProduct(&quot;ΦA4Φ&quot;)&gt; 
        '''&lt;Assembly: AssemblyCopyright(&quot;ΦA5Φ&quot;)&gt; 
        '''&lt;Assembly: AssemblyTrademark(&quot;ΦA6Φ&quot;)&gt; 
        '''&lt;Assembly: AssemblyVersion(&quot;1.4.1.7&quot;)&gt; 
        '''&lt;Assembly: AssemblyFileVersion(&quot;1.5.1.7&quot;)&gt; 
        '''Namespace ΦN1Φ
        '''    Public Class ΦM1Φ
        '''        Public Shared Sub Main()
        '''            Threading.Thread.Sleep(1500)
        '''         [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property bubby() As String
            Get
                Return ResourceManager.GetString("bubby", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property ResHacker() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("ResHacker", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
    End Module
End Namespace
